import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AuthProvider } from "./context/AuthContext";
import AOSProvider from "./context/AOS";
import LoadingWrapper from "./context/LoadingWrapper";

const outfit = Outfit({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className}`}>
          <LoadingWrapper>
            <AOSProvider>
              <AuthProvider>{children}</AuthProvider>
            </AOSProvider>
          </LoadingWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
